export const LAY_DANH_SACH_PHIM = 'LAY_DANH_SACH_PHIM'
export const SET_PHIM_DANG_CHIEU = 'SET_PHIM_DANG_CHIEU'
export const SET_PHIM_SAP_CHIEU = 'SET_PHIM_SAP_CHIEU'
export const LAY_CHI_TIET_PHIM = 'LAY_CHI_TIET_PHIM'